name: Rust

on:
  push:
      branches:
        - main

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
      - name: rust setup
        uses: actions/checkout@v2
      - name: install cargo-audit
        run: cargo install cargo-audit
      - name: build
        run: cargo build --verbose
      - name: tests
        run: cargo test --verbose
      - name: clippy
        run: cargo clippy --verbose -- -D warnings
      - name: audit
        run: cargo audit
